### ISSUE TITLE
IOErroro: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Yannik25** [cgoillot/GPX_Correct#2]
Hallo, 
i am getting following error while trying to convert my files.
It's not the only specific file, because when I delete it the next file will get the error message.

python C:\Runtastic\GPX_Correct.py
('Correcting', 'Runtastic 2013-05-07 07.22.44 Bikin')
Traceback (most recent call last):
  File "C:\Runtastic\GPX_Correct.py", line 189, in <module>
    TimeCorrect(listfile[i], newfilename, 0)
  File "C:\Runtastic\GPX_Correct.py", line 41, in TimeCorrect
    tree = ET.parse(f)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'Runtastic 2013-05-07 07.22.44 Biking.gpx'

**Comment by cgoillot** [comment]
Hello, I think you are not in the C:\Runtastic folder when you run the
program.

Can you try to run this instead?
*cd C:\Runtastic\*
*python GPX_Correct.py*

Don't hesitate to come back to me.
Thanks,
Clement

2017-11-09 9:32 GMT+01:00 Yannik25 <notifications@github.com>:

**Comment by Yannik25** [comment]
Thanks for your reply,

Now I got the same Error from issue #1 

But with his fix in line 94 it worked.

Great work thanks.
